ENV_WORK_DIR=$(pwd)

cat <<EOF > .env
POSTGRES_PASSWORD="Boyluu96"
POSTGRES_USER="ken"
POSTGRES_DB="main"
VIRTUAL_ENV="$ENV_WORK_DIR/.venv"
DBT_PROFILES_DIR="$ENV_WORK_DIR/dbt_project"
DAGSTER_HOME="$ENV_WORK_DIR/src/src_dagster"
PYTHONPATH="$ENV_WORK_DIR/src"
ENV_WORK_DIR="$ENV_WORK_DIR"

EOF